# Generated by Django 3.1.5 on 2021-01-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="log_subdomain",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
