# Generated by Django 3.1.5 on 2021-01-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_log_subdomain"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="log_subdomain", new_name="logbook_prefix",),
    ]
