# Generated by Django 3.1.5 on 2021-01-10 15:40

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210110_1414"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="logbook_title", field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_imge",
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
    ]
