# Generated by Django 3.1.5 on 2021-01-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210110_1540"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="profile_imge", new_name="profile_image",),
    ]
