# Generated by Django 3.1.5 on 2021-01-10 15:59

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20210110_1557"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="logbook_header_image",
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
    ]
