# Generated by Django 3.1.5 on 2021-01-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210112_1708"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="logbook_prefix", new_name="logbook_subdomain",),
    ]
