# Generated by Django 3.1.5 on 2021-01-05 19:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import tours.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True, max_length=102400, null=True)),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to=tours.models.upload_to)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_tours.tour_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={"ordering": ["-id"],},
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, max_length=102400, null=True)),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to=tours.models.upload_to)),
                ("gpx_file", models.FileField(blank=True, null=True, upload_to=tours.models.upload_to)),
                ("geojson_preview", models.FileField(blank=True, null=True, upload_to=tours.models.upload_to)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("moving_time_s", models.IntegerField(blank=True, null=True)),
                ("stopped_time_s", models.IntegerField(blank=True, null=True)),
                ("distance_km", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("uphill_m", models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ("downhill_m", models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ("max_speed_km_per_h", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("avg_speed_km_per_h", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_tours.track_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                ("tour", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="tours.tour")),
            ],
            options={"ordering": ["start_date"],},
        ),
        migrations.CreateModel(
            name="CyclingTour",
            fields=[
                (
                    "tour_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tours.tour",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("R", "Road"), ("T", "Touring"), ("M", "Mountain"), ("G", "Gravel")],
                        db_index=True,
                        max_length=1,
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("tours.tour",),
        ),
        migrations.CreateModel(
            name="CyclingTrack",
            fields=[
                (
                    "track_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tours.track",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("tours.track",),
        ),
    ]
