# Generated by Django 3.1.5 on 2021-01-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="track", old_name="geojson_preview", new_name="geojson",),
    ]
