# Generated by Django 3.1.5 on 2021-01-05 21:03

import django.db.models.deletion
from django.db import migrations, models

import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_auto_20210105_1959"),
    ]

    operations = [
        migrations.RemoveField(model_name="track", name="cover_image",),
        migrations.CreateModel(
            name="TrackImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.ImageField(upload_to=tours.models.upload_to)),
                ("track", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tours.track")),
            ],
        ),
    ]
