# Generated by Django 3.1.5 on 2021-01-04 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0003_remove_stage_gpx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="tour",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="tours.tour"),
        ),
    ]
