# Generated by Django 3.1.5 on 2021-01-06 17:24

from django.db import migrations, models

import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0003_auto_20210105_2103"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackimage",
            name="latitude",
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="trackimage",
            name="longitude",
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="tour", name="cover_image", field=models.ImageField(null=True, upload_to=tours.models.upload_to),
        ),
        migrations.AlterField(
            model_name="tour", name="description", field=models.TextField(max_length=102400, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="avg_speed_km_per_h",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="track", name="description", field=models.TextField(max_length=102400, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="distance_km",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="downhill_m",
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="track", name="geojson", field=models.FileField(null=True, upload_to=tours.models.upload_to),
        ),
        migrations.AlterField(
            model_name="track", name="gpx_file", field=models.FileField(null=True, upload_to=tours.models.upload_to),
        ),
        migrations.AlterField(
            model_name="track",
            name="max_speed_km_per_h",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(model_name="track", name="moving_time_s", field=models.IntegerField(null=True),),
        migrations.AlterField(model_name="track", name="stopped_time_s", field=models.IntegerField(null=True),),
        migrations.AlterField(
            model_name="track", name="uphill_m", field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
