# Generated by Django 3.1.5 on 2021-01-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_auto_20210106_1724"),
    ]

    operations = [
        migrations.RenameModel(old_name="TrackImage", new_name="TrackPhoto",),
    ]
