# Generated by Django 3.1.4 on 2020-12-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip", name="end_date", field=models.DateField(default="2020-01-01"), preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip", name="start_date", field=models.DateField(default="2020-01-01"), preserve_default=False,
        ),
    ]
