# Generated by Django 3.1.4 on 2020-12-28 20:46

from django.db import migrations, models

import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_auto_20201227_1756"),
    ]

    operations = [
        migrations.AlterModelOptions(name="trip", options={"ordering": ["-id"]},),
        migrations.AlterField(
            model_name="trip",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to=trips.models.upload_to),
        ),
        migrations.AlterField(
            model_name="trip", name="description", field=models.TextField(blank=True, max_length=102400, null=True),
        ),
    ]
