# Generated by Django 3.1.4 on 2020-12-29 15:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("trips", "0003_auto_20201228_2046"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("gpx_file", models.FileField(blank=True, null=True, upload_to=trips.models.upload_to)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("motion_time_s", models.IntegerField(blank=True, null=True)),
                ("stopped_time_s", models.IntegerField(blank=True, null=True)),
                ("distance_km", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("uphill_m", models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ("downhill_m", models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ("max_speed_m_per_s", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("avg_speed_m_per_s", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_trips.stage_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                ("trip", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="trips.trip")),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
        ),
        migrations.CreateModel(
            name="CycleStage",
            fields=[
                (
                    "stage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trips.stage",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("trips.stage",),
        ),
    ]
