# Generated by Django 3.1.4 on 2020-12-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("trips", "0005_auto_20201229_2037"),
    ]

    operations = [
        migrations.RenameModel(old_name="CycleStage", new_name="CyclingStage",),
    ]
