# Generated by Django 3.1.4 on 2020-12-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_auto_20201229_2040"),
    ]

    operations = [
        migrations.RenameField(model_name="stage", old_name="motion_time_s", new_name="moving_time_s",),
    ]
