# Generated by Django 3.1.4 on 2020-12-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_auto_20201230_1408"),
    ]

    operations = [
        migrations.RenameField(model_name="stage", old_name="avg_speed_m_per_s", new_name="avg_speed_km_per_h",),
        migrations.RenameField(model_name="stage", old_name="max_speed_m_per_s", new_name="max_speed_km_per_h",),
    ]
