# Generated by Django 3.1.4 on 2020-12-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_auto_20201230_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="name",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
    ]
