# Generated by Django 3.1.4 on 2021-01-02 21:03

from django.db import migrations, models

import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0009_stage_name"),
    ]

    operations = [
        migrations.AlterModelOptions(name="stage", options={"ordering": ["start_date"]},),
        migrations.AddField(
            model_name="stage",
            name="geojson_preview",
            field=models.FileField(blank=True, null=True, upload_to=trips.models.upload_to),
        ),
    ]
