# Generated by Django 3.1.4 on 2021-01-02 21:04

from django.db import migrations, models

import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0010_auto_20210102_2103"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="gpx",
            field=models.FileField(blank=True, null=True, upload_to=trips.models.upload_to),
        ),
    ]
